# 12 services total
SERVICES_STATUS = [
    {
        "service": "payments-gateway",
        "status": "degraded",
        "degraded_since": "2025-02-25T14:23:00Z",
        "affected_requests_pct": 12,
        "affected_users": 1200,
        "affected_departments": ["sales", "finance", "operations"],
        "revenue_impact": "$45,000/hour",
        "notes": "Elevated 5xx errors from upstream dependency; partial traffic shedding enabled.",
        "on_call": "Priya Nair",
    },
    {
        "service": "auth-service",
        "status": "healthy",
        "affected_users": 380,
        "affected_departments": ["hr", "operations"],
        "revenue_impact": "$8,500/hour",
        "notes": "Elevated latency (p95 +38%) but within error budget; monitoring closely.",
        "on_call": "Bilal Ahmed",
    },
    {
        "service": "user-service",
        "status": "healthy",
        "affected_users": 0,
        "affected_departments": [],
        "revenue_impact": "$0/hour",
    },
    {
        "service": "orders-service",
        "status": "healthy",
        "affected_users": 0,
        "affected_departments": [],
        "revenue_impact": "$0/hour",
    },
    {
        "service": "ledger-service",
        "status": "healthy",
        "affected_users": 0,
        "affected_departments": [],
        "revenue_impact": "$0/hour",
    },
    {
        "service": "notifications",
        "status": "healthy",
        "affected_users": 0,
        "affected_departments": [],
        "revenue_impact": "$0/hour",
    },
    {
        "service": "reporting-api",
        "status": "healthy",
        "affected_users": 0,
        "affected_departments": [],
        "revenue_impact": "$0/hour",
    },
    {
        "service": "risk-engine",
        "status": "healthy",
        "affected_users": 0,
        "affected_departments": [],
        "revenue_impact": "$0/hour",
    },
    {
        "service": "web-frontend",
        "status": "healthy",
        "affected_users": 0,
        "affected_departments": [],
        "revenue_impact": "$0/hour",
    },
    {
        "service": "admin-portal",
        "status": "healthy",
        "affected_users": 0,
        "affected_departments": [],
        "revenue_impact": "$0/hour",
    },
    {
        "service": "data-pipeline",
        "status": "healthy",
        "affected_users": 0,
        "affected_departments": [],
        "revenue_impact": "$0/hour",
    },
    {
        "service": "audit-service",
        "status": "healthy",
        "affected_users": 0,
        "affected_departments": [],
        "revenue_impact": "$0/hour",
    },
]

ACTIVE_INCIDENTS = [
    {
        "incident_id": "inc_p1_042",
        "severity": "P1",
        "service": "payments-gateway",
        "started_at": "2025-02-25T14:23:00Z",
        "last_update_at": "2025-02-25T15:07:00Z",
        "owner": "Priya Nair",
        "status": "mitigating",
        "impact_summary": "12% of payment attempts returning 5xx; intermittent timeouts in EU region.",
        "timeline": [
            "14:23Z - Alert triggered: 5xx rate exceeded threshold (payments-gateway)",
            "14:28Z - On-call engaged; initial mitigation: increased retries + circuit breaker tuned.",
            "14:41Z - Partial traffic routed to secondary region; error rate reduced but not resolved.",
            "15:07Z - Vendor escalation initiated (CloudScale Solutions); awaiting response.",
        ],
    },
    {
        "incident_id": "inc_p2_017",
        "severity": "P2",
        "service": "auth-service",
        "started_at": "2025-02-25T10:12:00Z",
        "last_update_at": "2025-02-25T14:55:00Z",
        "owner": "Bilal Ahmed",
        "status": "investigating",
        "impact_summary": "Elevated latency on token issuance; no major error rate increase.",
        "timeline": [
            "10:12Z - Latency anomaly detected on auth-service (p95).",
            "10:35Z - Cache hit-rate drop identified; reviewing recent config changes.",
            "14:55Z - Rollback candidate prepared; pending change window approval.",
        ],
    },
]


CAPACITY = [
    {
        "cluster": "prod-eu-1",
        "cpu_util_pct": 78,
        "memory_util_pct": 71,
        "pods_running": 942,
        "services": {
            "payments-gateway": {"can_scale": False},
            "auth-service": {"can_scale": True},
            "orders-service": {"can_scale": True},
            "web-frontend": {"can_scale": True},
        },
        "notes": "Headroom limited; autoscaler near max for payments-gateway.",
    },
    {
        "cluster": "prod-us-1",
        "cpu_util_pct": 62,
        "memory_util_pct": 58,
        "pods_running": 811,
        "services": {
            "payments-gateway": {"can_scale": True},
            "auth-service": {"can_scale": True},
            "user-service": {"can_scale": True},
            "admin-portal": {"can_scale": True},
        },
        "notes": "Stable; can take spillover traffic if needed.",
    },
    {
        "cluster": "prod-apac-1",
        "cpu_util_pct": 55,
        "memory_util_pct": 49,
        "pods_running": 603,
        "services": {
            "notifications": {"can_scale": True},
            "reporting-api": {"can_scale": True},
            "risk-engine": {"can_scale": True},
            "data-pipeline": {"can_scale": True},
        },
        "notes": "Healthy; no current alerts.",
    },
]

RECENT_DEPLOYMENTS = [
    {
        "deployment_id": "dep_2025_901",
        "service": "payments-gateway",
        "version": "v2.18.4",
        "deployed_at": "2025-02-25T13:10:00Z",
        "status": "success",
        "deployed_by": "Omar Siddiqui",
        "notes": "Routine dependency bump; rollout completed 13:18Z.",
    },
    {
        "deployment_id": "dep_2025_900",
        "service": "auth-service",
        "version": "v3.7.2",
        "deployed_at": "2025-02-25T09:02:00Z",
        "status": "success",
        "deployed_by": "Bilal Ahmed",
        "notes": "Config update: cache TTL adjustment.",
    },
    {
        "deployment_id": "dep_2025_899",
        "service": "reporting-api",
        "version": "v1.12.0",
        "deployed_at": "2025-02-24T20:41:00Z",
        "status": "success",
        "deployed_by": "Priya Nair",
        "notes": "Performance improvements for monthly exports.",
    },
    {
        "deployment_id": "dep_2025_898",
        "service": "data-pipeline",
        "version": "v5.3.1",
        "deployed_at": "2025-02-24T18:10:00Z",
        "status": "success",
        "deployed_by": "Hassan Raza",
    },
    {
        "deployment_id": "dep_2025_897",
        "service": "risk-engine",
        "version": "v4.0.6",
        "deployed_at": "2025-02-24T16:05:00Z",
        "status": "success",
        "deployed_by": "Sara Williams",
    },
    {
        "deployment_id": "dep_2025_896",
        "service": "notifications",
        "version": "v2.2.0",
        "deployed_at": "2025-02-24T14:22:00Z",
        "status": "failed",
        "deployed_by": "Emily Chen",
        "notes": "Rollback executed due to webhook auth regression.",
    },
    # Keep list at 10 entries total
    {
        "deployment_id": "dep_2025_895",
        "service": "user-service",
        "version": "v8.1.9",
        "deployed_at": "2025-02-24T11:18:00Z",
        "status": "success",
        "deployed_by": "Omar Siddiqui",
    },
    {
        "deployment_id": "dep_2025_894",
        "service": "orders-service",
        "version": "v6.4.3",
        "deployed_at": "2025-02-24T09:55:00Z",
        "status": "success",
        "deployed_by": "Emily Chen",
    },
    {
        "deployment_id": "dep_2025_893",
        "service": "ledger-service",
        "version": "v3.9.0",
        "deployed_at": "2025-02-23T22:40:00Z",
        "status": "success",
        "deployed_by": "Bilal Ahmed",
    },
    {
        "deployment_id": "dep_2025_892",
        "service": "audit-service",
        "version": "v1.5.7",
        "deployed_at": "2025-02-23T19:12:00Z",
        "status": "success",
        "deployed_by": "Priya Nair",
    },
]
