VENDORS = [
    {
        "vendor_id": "ven_001",
        "name": "CloudScale Solutions",
        "category": "cloud",
        "risk_tier": "medium",
        "primary_contact": "Hina Farooq",
        "email": "hina.farooq@cloudscalesolutions.com",
        "status": "approved",
    },
    {
        "vendor_id": "ven_002",
        "name": "SecureNet Systems",
        "category": "professional_services",
        "risk_tier": "low",
        "primary_contact": "James Patel",
        "email": "j.patel@securenetsystems.com",
        "status": "approved",
    },
    {
        "vendor_id": "ven_003",
        "name": "DataForge Analytics",
        "category": "professional_services",
        "risk_tier": "low",
        "primary_contact": "Amna Siddiq",
        "email": "amna.siddiq@dataforge.io",
        "status": "approved",
    },
    {
        "vendor_id": "ven_004",
        "name": "IronRack Hardware",
        "category": "hardware",
        "risk_tier": "medium",
        "primary_contact": "Tomas Alvarez",
        "email": "t.alvarez@ironrackhw.com",
        "status": "approved",
    },
    {
        "vendor_id": "ven_005",
        "name": "NetPulse Monitoring",
        "category": "professional_services",
        "risk_tier": "low",
        "primary_contact": "Sana Iqbal",
        "email": "sana.iqbal@netpulse.com",
        "status": "approved",
    },
    {
        "vendor_id": "ven_006",
        "name": "Vertex CDN",
        "category": "cloud",
        "risk_tier": "medium",
        "primary_contact": "Olivia Brown",
        "email": "olivia.brown@vertexcdn.com",
        "status": "approved",
    },
    {
        "vendor_id": "ven_007",
        "name": "QuantumOps Consulting",
        "category": "professional_services",
        "risk_tier": "high",
        "primary_contact": "Faisal Mahmood",
        "email": "f.mahmood@quantumops.co",
        "status": "under_review",
    },
    {
        "vendor_id": "ven_008",
        "name": "ShieldKey IAM",
        "category": "cloud",
        "risk_tier": "low",
        "primary_contact": "Mei Lin",
        "email": "mei.lin@shieldkey.com",
        "status": "approved",
    },
]

# 3 contracts expiring within 90 days
EXPIRING_CONTRACTS = [
    {
        "contract_id": "ct_2025_210",
        "vendor": "CloudScale Solutions",
        "value_usd": 220000,
        "expires_on": "2025-04-18",
        "days_remaining": 52,
        "owner": "Ayesha Khan",
        "renewal_risk": "high",
        "notes": "Critical dependency for payments-gateway. Renewal decision blocked pending invoice approval ($84k) in Finance.",
    },
    {
        "contract_id": "ct_2025_198",
        "vendor": "IronRack Hardware",
        "value_usd": 64000,
        "expires_on": "2025-03-28",
        "days_remaining": 31,
        "owner": "Bilal Ahmed",
        "renewal_risk": "medium",
        "notes": "Rack expansion option expires end of month; capacity headroom tightening in prod-eu-1.",
    },
    {
        "contract_id": "ct_2025_177",
        "vendor": "NetPulse Monitoring",
        "value_usd": 48000,
        "expires_on": "2025-05-10",
        "days_remaining": 74,
        "owner": "Sara Williams",
        "renewal_risk": "low",
        "notes": "Renewal expected; tool supports anomaly detection alerts for API error spikes.",
    },
]